import { appendFileSync, readFileSync as fsReadFileSync } from "node:fs";

import { scanDeprecatedApi, scanHelmValues, scanPodSecurity, scanRbac, type Finding, type Severity } from "./scanners.js";

export type FailOn = "high" | "medium" | "none";

export interface RunnerInputs {
  manifests_dir?: string;
  chart_dir?: string;
  fail_on?: string;
  comment_on_pr?: string;
  github_token?: string;
}

export interface RunnerEnv {
  inputs: RunnerInputs;
  GITHUB_OUTPUT?: string;
  GITHUB_EVENT_NAME?: string;
  GITHUB_REPOSITORY?: string;
  GITHUB_EVENT_PATH?: string;
  readFile?: (path: string) => string;
  write?: (line: string) => void;
  postComment?: (args: { token: string; repo: string; issueNumber: number; body: string }) => Promise<void>;
}

export interface RunnerResult {
  exitCode: 0 | 1;
  findings: Finding[];
  counts: Record<Severity, number>;
  reason?: string;
  commentPosted: boolean;
}

const FAIL_VALUES: FailOn[] = ["high", "medium", "none"];

function severityRank(s: Severity): number {
  return s === "high" ? 0 : s === "medium" ? 1 : s === "low" ? 2 : 3;
}

export async function run(env: RunnerEnv): Promise<RunnerResult> {
  const manifestsDir = env.inputs.manifests_dir;
  if (!manifestsDir) throw new Error(`input "manifests-dir" is required`);
  const failOn = (env.inputs.fail_on ?? "high") as FailOn;
  if (!FAIL_VALUES.includes(failOn)) throw new Error(`fail-on must be one of: ${FAIL_VALUES.join(", ")}`);
  const commentMode = env.inputs.comment_on_pr ?? "auto";
  const token = env.inputs.github_token ?? "";

  const write = env.write ?? ((line) => process.stdout.write(`${line}\n`));

  const findings: Finding[] = [
    ...scanDeprecatedApi(manifestsDir),
    ...scanRbac(manifestsDir),
    ...scanPodSecurity(manifestsDir)
  ];
  if (env.inputs.chart_dir) findings.push(...scanHelmValues(env.inputs.chart_dir));

  // Sort findings: high first, then scanner, then source.
  findings.sort((a, b) => {
    if (a.severity !== b.severity) return severityRank(a.severity) - severityRank(b.severity);
    if (a.scanner !== b.scanner) return a.scanner.localeCompare(b.scanner);
    return a.source.localeCompare(b.source);
  });

  const counts: Record<Severity, number> = { high: 0, medium: 0, low: 0, info: 0 };
  for (const f of findings) counts[f.severity] += 1;

  const markdown = renderMarkdown(findings, counts, manifestsDir, env.inputs.chart_dir);
  write(`\n${markdown}\n`);

  setOutput(env, "total-findings", String(findings.length));
  setOutput(env, "high", String(counts.high));
  setOutput(env, "medium", String(counts.medium));
  setOutput(env, "low", String(counts.low));

  const wantsComment = commentMode === "true" || (commentMode === "auto" && env.GITHUB_EVENT_NAME === "pull_request");
  let commentPosted = false;
  let reason: string | undefined;
  if (wantsComment) {
    if (!token) reason = "no github-token provided";
    else if (!env.GITHUB_EVENT_PATH) reason = "no GITHUB_EVENT_PATH";
    else if (!env.GITHUB_REPOSITORY) reason = "no GITHUB_REPOSITORY";
    else {
      const event = JSON.parse((env.readFile ?? readSync)(env.GITHUB_EVENT_PATH)) as { number?: number; pull_request?: { number?: number } };
      const issueNumber = event.number ?? event.pull_request?.number;
      if (!issueNumber) reason = "no PR number in event payload";
      else {
        const poster = env.postComment ?? defaultPostComment;
        await poster({ token, repo: env.GITHUB_REPOSITORY, issueNumber, body: `### K8s pre-merge gate\n\n${markdown}\n\n_Generated by [k8s-pre-merge-action](https://github.com/mizcausevic-dev/k8s-pre-merge-action)._` });
        commentPosted = true;
      }
    }
  }

  let exitCode: 0 | 1 = 0;
  if (failOn === "high" && counts.high > 0) exitCode = 1;
  else if (failOn === "medium" && counts.high + counts.medium > 0) exitCode = 1;

  return { exitCode, findings, counts, commentPosted, reason };
}

function readSync(path: string): string {
  return fsReadFileSync(path, "utf8");
}

function setOutput(env: RunnerEnv, key: string, value: string): void {
  if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

function renderMarkdown(findings: Finding[], counts: Record<Severity, number>, manifestsDir: string, chartDir?: string): string {
  const lines: string[] = [];
  const ok = counts.high === 0;
  lines.push(ok ? `# K8s pre-merge gate ✅` : `# K8s pre-merge gate ❌`);
  lines.push(``);
  lines.push(`Manifests: \`${manifestsDir}\``);
  if (chartDir) lines.push(`Chart: \`${chartDir}\``);
  lines.push(``);
  lines.push(`- 🔴 high: **${counts.high}** · 🟠 medium: ${counts.medium} · 🟡 low: ${counts.low}`);

  if (findings.length === 0) {
    lines.push(``);
    lines.push(`No findings.`);
    return lines.join("\n");
  }
  lines.push(``);
  lines.push(`| severity | scanner | code | resource | source | message |`);
  lines.push(`|---|---|---|---|---|---|`);
  for (const f of findings) {
    const icon = f.severity === "high" ? "🔴" : f.severity === "medium" ? "🟠" : "🟡";
    lines.push(`| ${icon} ${f.severity} | \`${f.scanner}\` | \`${f.code}\` | \`${f.subject ?? "—"}\` | \`${f.source}\` | ${f.message} |`);
  }
  return lines.join("\n");
}

async function defaultPostComment(args: { token: string; repo: string; issueNumber: number; body: string }): Promise<void> {
  const r = await fetch(`https://api.github.com/repos/${args.repo}/issues/${args.issueNumber}/comments`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${args.token}`,
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({ body: args.body })
  });
  if (!r.ok) throw new Error(`GitHub API comment failed: ${r.status} ${await r.text()}`);
}
